from pathlib import Path
from typing import Final

RGB = tuple[int, int, int]
RGBA = tuple[int, int, int, int]
Ink = RGB | RGBA

CARD_SIZE: Final[tuple[int, int]] = (1080, 1350)
CARD_WIDTH, CARD_HEIGHT = CARD_SIZE

CARD_FORMAT: Final = "JPEG"
CARD_SUFFIX: Final = "jpg"
CARD_QUALITY: Final = 92

TEMPLATES_DIR: Final[Path] = Path(__file__).parent / "templates"

BACKGROUND_NEUTRAL: Final = "bg_neutral.jpg"
BACKGROUND_UNDERCOVER: Final = "bg_undercover.jpg"

FONT_REGULAR: Final = "regular.ttf"
FONT_BOLD: Final = "bold.otf"

SAFE_MARGIN: Final = 96
GLOW_BLEED: Final = 32
CONTENT_WIDTH: Final = CARD_WIDTH - 2 * (SAFE_MARGIN + GLOW_BLEED)
CONTENT_LEFT: Final = SAFE_MARGIN + GLOW_BLEED
CONTENT_RIGHT: Final = CARD_WIDTH - SAFE_MARGIN - GLOW_BLEED
LAMP_CENTER: Final = round(CARD_HEIGHT * 0.46)

INK: Final[RGB] = (247, 248, 252)
INK_MUTED: Final[RGB] = (152, 172, 208)
INK_MUTED_WARM: Final[RGB] = (214, 156, 158)

GLOW_COLD: Final[RGB] = (74, 122, 194)
GLOW_WARM: Final[RGB] = (186, 58, 60)

SHADOW_COLOR: Final[RGB] = (0, 0, 0)
SHADOW_BLUR: Final = 8.0
SHADOW_OFFSET: Final[tuple[int, int]] = (0, 5)
SHADOW_OPACITY: Final = 0.85

GLOW_BLUR: Final = 7.0
GLOW_OPACITY: Final = 0.45

CAPTION_SIZE: Final = 36
CAPTION_TRACKING: Final = 11
CAPTION_RULE_LENGTH: Final = 64
CAPTION_RULE_GAP: Final = 26
CAPTION_RULE_WIDTH: Final = 2

OWNER_SIZE: Final = 50
FOOTNOTE_SIZE: Final = 32

STAMP_TEXT_SIZE: Final = 60
STAMP_TRACKING: Final = 10
STAMP_PADDING_X: Final = 46
STAMP_PADDING_Y: Final = 24
STAMP_ANGLE: Final = 3.0
STAMP_BORDER: Final = 5
STAMP_INSET: Final = 10
STAMP_INNER_BORDER: Final = 2
STAMP_SUPERSAMPLE: Final = 2
STAMP_INK: Final[RGBA] = (255, 244, 245, 236)
STAMP_FILL: Final[RGBA] = (28, 6, 10, 104)

WORDMARK_SIZE: Final = 26
WORDMARK_TRACKING: Final = 16
WORDMARK_INK: Final[RGBA] = (238, 240, 248, 120)

PROMO_SIZE: Final = 24
PROMO_TRACKING: Final = 6
PROMO_INK: Final[RGBA] = (226, 230, 242, 150)
FOOTER_GAP: Final = 16

FOOTER_BAND: Final = WORDMARK_SIZE + FOOTER_GAP + PROMO_SIZE
CONTENT_HEIGHT: Final = CARD_HEIGHT - 2 * (SAFE_MARGIN + GLOW_BLEED) - FOOTER_BAND

HEADLINE_MAX_SIZE: Final = 120
HEADLINE_MIN_SIZE: Final = 52
HEADLINE_MAX_LINES: Final = 2

HINT_MAX_SIZE: Final = 56
HINT_MIN_SIZE: Final = 32
HINT_MAX_LINES: Final = 4

ROSTER_MAX_SIZE: Final = 44
ROSTER_MIN_SIZE: Final = 26
ROSTER_SIZE_STEP: Final = 2
ROSTER_LINE_SPACING: Final = 1.34
ROSTER_TAG_RATIO: Final = 0.62
ROSTER_TAG_MIN_SIZE: Final = 20
ROSTER_TAG_TRACKING: Final = 6
ROSTER_COLUMN_GAP: Final = 32
ROSTER_SPLIT_GAP: Final = 40
ROSTER_MAX_COLUMNS: Final = 2
ROSTER_OUT_INK: Final[RGB] = (126, 138, 162)
ROSTER_SPY_INK: Final[RGB] = (226, 118, 120)

RESULT_WORD_MAX_LINES: Final = 2

CASE_SIZE: Final = 28
BANNER_SIZE: Final = 56
METRICS_SIZE: Final = 28

SUMMARY_WORD_MAX_SIZE: Final = 72
SUMMARY_WORD_MIN_SIZE: Final = 40
SUMMARY_WORD_MAX_LINES: Final = 2

SUMMARY_HINT_MAX_SIZE: Final = 32
SUMMARY_HINT_MIN_SIZE: Final = 22
SUMMARY_HINT_MAX_LINES: Final = 3

SUMMARY_BANNER_SPACE: Final = 40
SUMMARY_SECTION_SPACE: Final = 48
SUMMARY_TIGHT_SPACE: Final = 24
SUMMARY_METRICS_SPACE: Final = 44
